"""add User table

Revision ID: d7fb5f758da1
Revises: 74fe76a9f457
Create Date: 2025-01-18 16:23:44.311286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd7fb5f758da1'
down_revision: Union[str, None] = '74fe76a9f457'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'memo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('memo', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
